-- What are the details of all cars purchased in the year 2022?
SELECT cars.car_id, cars.make, cars.type, cars.style, cars.cost_$
FROM cars JOIN sales ON cars.car_id = sales.car_id
WHERE purchase_date BETWEEN '2022-01-01' AND '2022-12-30'


-- What is the total number of cars sold by each salesperson?
Select sales.salesman_id, Count(sales.sale_id)
from sales
Group by sales.salesman_id


--  What is the total revenue generated by each salesperson?
select sales.salesman_id, sum(cars.cost_$) 
from sales
Join cars on sales.car_id = cars.car_id
Group by sales.salesman_id


-- What are the details of the cars sold by each salesperson?
SELECT sales.salesman_id,	cars.car_id, cars.make, cars.type, cars.style, cars.cost_$
FROM cars JOIN sales ON cars.car_id = sales.car_id
Group by salesman_id


-- What is the total revenue generated by each car type?
Select sales.car_id, sum(cars.cost_$)
from cars JOIN sales ON cars.car_id = sales.car_id
Group by sales.car_id


-- What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
SELECT cars.car_id, cars.make, cars.type, cars.style, cars.cost_$, salespersons.name
FROM cars JOIN sales ON cars.car_id = sales.car_id
Join salespersons On sales.salesman_id = salespersons.salesman_id
Where salespersons.name = 'Emily Wong' and purchase_date between '2021-01-01' AND '2021-12-30' 


-- What is the total revenue generated by the sales of hatchback cars?
SELECT cars.car_id, cars.style, sum(cars.cost_$)
FROM cars 
JOIN sales ON cars.car_id = sales.car_id
Group by cars.style
Having cars.style = 'Hatchback'


-- What is the total revenue generated by the sales of SUV cars in the year 2022?
select cars.style, sum(cars.cost_$)
from cars 
JOIN sales on sales.car_id = cars.car_id
Where cars.style = 'SUV'


-- What is the name and city of the salesperson who sold the most number of cars in the year 2023?
SELECT salespersons.name, salespersons.city, COUNT(sales.salesman_id) 
FROM salespersons 
JOIN sales 
ON sales.salesman_id = salespersons.salesman_id 
WHERE sales.purchase_date BETWEEN '2023-01-01' AND '2023-12-30' 
GROUP BY sales.salesman_id 
ORDER BY COUNT(sales.salesman_id) DESC
LIMIT 1;


-- What is the name and age of the salesperson who generated the highest revenue in the year 2022?
SELECT salespersons.name, salespersons.age, sum(cars.cost_$)
FROM salespersons 
JOIN sales ON sales.salesman_id = salespersons.salesman_id 
JOIN cars ON cars.car_id = sales.car_id 
WHERE sales.purchase_date BETWEEN '2022-01-01' AND '2022-12-30' 
GROUP BY sales.salesman_id 
ORDER BY sum(cars.cost_$) DESC
Limit 1;