-- 1. What are the names of all the countries in the country table?
Select country_name 
from country


-- 2. What is the total number of customers in the customers table?
Select count(*) 
from customers


-- 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
Select avg(age) from customers
where can_email = "yes"


-- 4. How many orders were made by customers aged 30 or older?
Select count(o.order_id) from orders as o
Join customers as c on c.customer_id = o.customer_id
Where c.age >= 30


-- 5. What is the total revenue generated by each product category?
select p.category, sum(p.price) from products as p
Join baskets as b on p.product_id = b.product_id 
group by b.product_id


-- 6. What is the average price of products in the 'food' category?
select avg(price) from products 
where category = "food"


-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?
Select sales_channel, count(*) from orders
group by sales_channel


-- 8.What is the date of the latest order made by a customer who can receive marketing emails?
select customer_id, first_shop from customers
where can_email = "yes"
order by first_shop desc
Limit 1
 
 
-- 9. What is the name of the country with the highest number of orders?
select c.country_name, sum(o.country_id) from country as c
Join orders as o on c.country_id = o.country_id
group by o.country_id
order by sum(o.country_id) desc
Limit 1
  
  
-- 10. What is the average age of customers who made orders in the 'vitamins' product category?
select avg(c.age) from customers as c
Join orders as o on c.customer_id = o.customer_id
Join baskets as b on o.order_id = b.order_id
Join products as p on b.product_id = p.product_id
where p.category = "vitamins"